[kvm_host]
37.27.173.224 ansible_user=root ansible_ssh_private_key_file=/Users/faridunismoilov/.ssh/kvm

[kafka]
kafka-01 ansible_host=192.168.150.150 node_id=1
kafka-02 ansible_host=192.168.150.151 node_id=2
kafka-03 ansible_host=192.168.150.152 node_id=3

[okd_workers]
okd-worker-0 ansible_host=192.168.150.103
okd-worker-1 ansible_host=192.168.150.105
okd-worker-2 ansible_host=192.168.150.153
okd-worker-3 ansible_host=192.168.150.154

[okd_masters]
okd-master-0 ansible_host=192.168.150.100
okd-master-1 ansible_host=192.168.150.101
okd-master-2 ansible_host=192.168.150.102

[okd_masters:vars]
ansible_user=core
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[kafka:vars]
ansible_user=root
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'


[clickhouse]
ch-node-01 ansible_host=192.168.150.140
ch-node-02 ansible_host=192.168.150.141
ch-node-03 ansible_host=192.168.150.142

[clickhouse:vars]
ansible_user=root
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[clickhouse_keeper]
keeper-01 ansible_host=192.168.150.143 server_id=1
keeper-02 ansible_host=192.168.150.144 server_id=2
keeper-03 ansible_host=192.168.150.145 server_id=3

[clickhouse_keeper:vars]
ansible_user=root
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[nfs_hosts]
nfs ansible_host=192.168.150.120

[nfs_hosts:vars]
ansible_user=nfs
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_ssh_pass=nfsforokd!@#
ansible_become_password=nfsforokd!@#

[psql_hosts]
psql ansible_host=192.168.150.121

[psql_hosts:vars]
ansible_user=psql
ansible_ssh_private_key_file=/Users/faridunismoilov/production-ready-clickhouse/ansible/keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyJump="root@37.27.173.224" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_become_password=psqlforokd!@#
