[kvm_host]
37.27.173.224 ansible_user=root ansible_ssh_private_key_file=/home/ff/.ssh/kvm

[kafka]
kafka-01 ansible_host=192.168.150.150 node_id=1
kafka-02 ansible_host=192.168.150.151 node_id=2
kafka-03 ansible_host=192.168.150.152 node_id=3

[okd_workers]
okd-worker-2 ansible_host=192.168.150.153
okd-worker-3 ansible_host=192.168.150.154

[kafka:vars]
ansible_user=root
ansible_ssh_private_key_file=keys/okd-bootstrap-key
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ff/.ssh/kvm -W %h:%p -q root@37.27.173.224" -o StrictHostKeyChecking=no'

